---
title: "Manuscript tables"
output:
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(knitr)
library(magrittr)

```

```{r}

temp <- expand.grid(
  Group = c("Carnivores", "Primates", "Ungulates"),
  Response = c("Host parasite richness", "Proportion closely transmitted", "Proportion microparasites"))
bestModSummary <- data.frame(
  temp,
  `Best model overall` = c("Complete", "Reduced", "Reduced", 
               "Reduced", "Complete", "Simple",
               "Complete", "Simple", "Reduced"), # the model with lowest AIC
  `Best complex model` = c("Complete", "Reduced", "Reduced", 
                   "Reduced", "Complete", "Reduced",
                   "Complete", "Complete", "Reduced")) # between the two complex models, which one has lower AIC


kable(bestModSummary, caption = "Best fit models for each group-response combination measured by AIC. Simple models only include threat status (NT or T) and log-citations. Complete complex models include all host traits and all interactions with threat status. Complete reduced models include some host traits and interactions as included if lower AIC. ")

```


```{r}

# model coefficients
setwd("~/IDEAS_JPEK")
source("Scripts/combined-workflow/script14_tablecalcs.R")

get_table <- function(brm_mod, Group){
  out <- as.data.frame(fixef(brm_mod))
  out=cbind(predictor=rownames(out), out)
  rownames(out) <- c()
  out=cbind(Group=Group, out)
  return(out)
}


richnessCoef <- rbind(get_table(modRichBest_list[[1]], "Carnivores"),
      get_table(modRichBest_list[[2]], "Primates"),
      get_table(modRichBest_list[[3]], "Ungulates"))

transmissCoef <- rbind(get_table(modParasTransBest_list[[1]], "Carnivores"),
      get_table(modParasTransBest_list[[2]], "Primates"),
      get_table(modParasTransBest_list[[3]], "Ungulates"))

typeCoef <- rbind(get_table(modParasTypeBest_list[[1]], "Carnivores"),
      get_table(modParasTypeBest_list[[2]], "Primates"),
      get_table(modParasTypeBest_list[[3]], "Ungulates"))

kable(richnessCoef, digits = 3, caption = "Model coefficients and highest posterior density region for best fit model of host-parasite species richness. ")

kable(transmissCoef, digits = 3, caption = "Model coefficients and highest posterior density region for best fit model of proportion of only closely transmitted parasites. ")

kable(typeCoef, digits = 3, caption = "Model coefficients and highest posterior density region for best fit model of proportion of only microparasites (bacteria, viruses, protozoa, fungi). ")



```

